name: build
permissions:
  contents: write
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.Scoop.csproj -o ./publish_output
          7z a -tzip "Flow.Launcher.Plugin.Scoop.zip" "./publish_output/*"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.Scoop.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
